### ISSUE TITLE
Data file is missing

### ISSUE THREAD

**Issue by joukevdveen** [DominiqueGeissler/Russian_Propaganda_on_social_media#1]
Hello, 
I am doing my bachelor thesis on reproducibility of social media research and chose to inspect this paper. I downloaded the code and the data but  noticed that 'M3bcd_ukrainian_tweets.csv' is missing.

**Comment by DominiqueGeissler** [comment]
Hello, thanks for pointing this out. I added the data as a .zip file and adjusted the code.
